### ISSUE TITLE
emulator exception due to invalid string size

### ISSUE THREAD

**Issue by AveyondFly** [zb3/freej2me#3]
The issue reproduction is pretty simple, keep press "5" and let the game keep going on, after serveral seconds, it will stuck at t a shock face screen as attachment.

Here is the snapshot and jar file.
![snapshot](https://github.com/zb3/freej2me/assets/12275486/b90620e5-f86c-4b81-9c88-2314416ee9a8)
[csl1.1.jar.txt](https://github.com/zb3/freej2me/files/14809419/csl1.1.jar.txt)

**Comment by zb3** [comment]
It looks like this happens because the `microedition.platform` property is by default set to `j2me`, but the game expects at least 8 characters present there (unless the value begins with `Sony`)
In J2ME-Loader, the default value seems to be `Nokia 6233` so it works.

I might change the default value if the nokia phone is selected (by default, it is), but I have a question.. currently if you enter settings (`Esc` key), change the phone type to Sony Ericsson and restart the emulator, it gets past this screen.. but since I don't understand Chinese, I don't know if the game works or not, could you please check that scenario? :D

**Comment by AveyondFly** [comment]
> It looks like this happens because the `microedition.platform` property is by default set to `j2me`, but the game expects at least 8 characters present there (unless the value begins with `Sony`) In J2ME-Loader, the default value seems to be `Nokia 6233` so it works.
> 
> I might change the default value if the nokia phone is selected (by default, it is), but I have a question.. currently if you enter settings (`Esc` key), change the phone type to Sony Ericsson and restart the emulator, it gets past this screen.. but since I don't understand Chinese, I don't know if the game works or not, could you please check that scenario? :D

Awesome, yes that works. So I assume j2me-load has a long string property. 
Thank you so much! Have a great day.

**Comment by zb3** [comment]
@AveyondFly, I've published RC4 release, could please you check if on that release this works out of the box even on the Nokia phone?

Also, thanks to your report I added more properties from J2ME-Loader like m3g version, I found that some games didn't run without that property and now they work :D

**Comment by AveyondFly** [comment]
> @AveyondFly, I've published RC4 release, could please you check if on that release this works out of the box even on the Nokia phone?
> 
> Also, thanks to your report I added more properties from J2ME-Loader like m3g version, I found that some games didn't run without that property and now they work :D

Yes, works fine even with Nokia. Thanks for the effort.
